/**
 * tern-node addon loading + generated type re-exports.
 *
 * The native binding lives at `src/bindings/tern-node` in the workspace and
 * is a CommonJS napi module (generated by napi-rs). It cannot be statically
 * imported from ESM, so it is loaded through `node:module` `createRequire` —
 * which works identically under Deno 2.x (Node-API addons are supported with
 * `--allow-ffi`) and Node.js. The exported type surface is re-exported from
 * the binding's generated `index.d.ts` so `@tern/core` consumers get the
 * canonical napi types without duplication.
 */

import { createRequire } from "node:module";
import process from "node:process";

// The generated napi declarations. Type-only import: erased at runtime, so
// this also resolves under Node's type stripping.
import type {
  ContentSize,
  HighlightSpanJs,
  KeyEvent,
  NodeHandle as NativeNodeHandle,
  TuiRenderer as NativeTuiRenderer,
  TuiRendererOptions,
} from "../../../src/bindings/tern-node/index.d.ts";

export type {
  ContentSize,
  HighlightSpanJs,
  KeyEvent,
  NodeHandle,
  TuiRenderer,
  TuiRendererOptions,
} from "../../../src/bindings/tern-node/index.d.ts";

/** The runtime surface of the loaded napi addon. */
export interface TernAddon {
  TuiRenderer: typeof NativeTuiRenderer;
  NodeHandle: typeof NativeNodeHandle;
  create_node: (type: string, props?: Record<string, unknown> | null) => NativeNodeHandle;
  /** Token-highlight `source` in `language` (a fence info string). */
  highlight: (language: string, source: string) => HighlightSpanJs[];
}

/** Relative from this file (`packages/core/src/`) up to the binding dir. */
const ADDON_PATH = "../../../src/bindings/tern-node/index.js";

let cached: TernAddon | null = null;

/**
 * @internal — test seam for `packages/core/src/index_test.ts`. Injects a fake
 * addon into the cache so `Renderer` dispatch can be exercised without the
 * native `.node` binding (Deno ESM exports are immutable, so the cached slot
 * is the seam). Pass `null` to reset back to lazy loading.
 */
export function setAddonForTesting(addon: TernAddon | null): void {
  cached = addon;
}

/**
 * Load the tern-node addon (cached). Tries the napi-generated loader first
 * (`index.js`), then falls back to requiring the platform `.node` directly.
 *
 * Throws with the combined loader errors when neither path resolves.
 */
export function loadAddon(): TernAddon {
  if (cached !== null) return cached;
  const require = createRequire(import.meta.url);
  const errors: string[] = [];
  const candidates = [
    ADDON_PATH,
    `../../../src/bindings/tern-node/tern-node.${process.platform}-${process.arch}.node`,
  ];
  for (const candidate of candidates) {
    try {
      cached = require(candidate) as TernAddon;
      return cached;
    } catch (err) {
      errors.push(`${candidate}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  throw new Error("could not load the tern-node addon:\n" + errors.join("\n"));
}
