/**
 * tern-node addon loading + generated type re-exports.
 *
 * The native binding lives at `src/bindings/tern-node` in the workspace and
 * is a CommonJS napi module (generated by napi-rs). It cannot be statically
 * imported from ESM, so it is loaded through `node:module` `createRequire` —
 * which works identically under Deno 2.x (Node-API addons are supported with
 * `--allow-ffi`) and Node.js. The exported type surface is re-exported from
 * the binding's generated `index.d.ts` so `@tern-tui/core` consumers get the
 * canonical napi types without duplication.
 */

import { createRequire } from "node:module";
import process from "node:process";

// The generated napi declarations. Type-only import: erased at runtime, so
// this also resolves under Node's type stripping. Only the types referenced
// below are imported; the full surface is re-exported by the `export type`
// block, which pulls directly from the binding module.
import type {
  HighlightSpanJs,
  NodeHandle as NativeNodeHandle,
  TuiRenderer as NativeTuiRenderer,
} from "@tern-tui/node";

export type {
  ContentSize,
  HighlightSpanJs,
  KeyEvent,
  NodeHandle,
  StyleRunJs,
  TuiRenderer,
  TuiRendererOptions,
} from "@tern-tui/node";

/** The runtime surface of the loaded napi addon. */
export interface TernAddon {
  TuiRenderer: typeof NativeTuiRenderer;
  NodeHandle: typeof NativeNodeHandle;
  create_node: (type: string, props?: Record<string, unknown> | null) => NativeNodeHandle;
  /** Token-highlight `source` in `language` (a fence info string). */
  highlight: (language: string, source: string) => HighlightSpanJs[];
  /**
   * The incremental highlighter class: buffers the accumulated source and
   * re-parses only the tail on each `append`, so a growing fence re-parses
   * just its new tail instead of the whole source (the one-shot `highlight`
   * above re-parses everything per call).
   */
  IncrementalHighlighter: new (language: string) => NativeIncrementalHighlighter;
}

/**
 * The result of one incremental `append`: the *complete* span stream over
 * the accumulated source (concatenating the span texts reconstructs it
 * exactly), plus the `[start, end)` byte range the incremental re-parse
 * actually reworked — absent before the first append, when there was no
 * previous parse to change. A pure tail append reports a range within the
 * appended chunk.
 */
export interface HighlightAppendJs {
  /** The complete span stream over the accumulated source. */
  spans: HighlightSpanJs[];
  /** The `[start, end)` byte range the re-parse reworked, absent before the
   * first append. */
  changed?: number[];
}

/** The native incremental highlighter instance surface. */
export interface NativeIncrementalHighlighter {
  /** Append `chunk`; returns the full stream over the accumulated source. */
  append(chunk: string): HighlightAppendJs;
  /** Drop the buffered source and tree; the next append is a fresh parse. */
  reset(): void;
}

/** Relative from this file (`packages/core/src/`) up to the binding dir. */
const ADDON_PATH = "../../../src/bindings/tern-node/index.js";

let cached: TernAddon | null = null;

/**
 * The addon test seam: inject a fake `TernAddon` into the load cache so
 * `Renderer` dispatch can be exercised without the native `.node` binding
 * (Deno ESM exports are immutable, so the cached slot is the seam — the one
 * place a fake can displace the real addon). Pass `null` to reset back to
 * lazy loading.
 *
 * This is a supported public seam, not just an internal test helper: a
 * consumer testing headlessly — snapshot tooling, CI, or a fake-addon suite
 * that records or scripts the native surface — can inject a fake addon
 * through this exported function and exercise the full JS layer without a
 * TTY, a compiled `.node` binary, or exports-map indirection. Injecting
 * through the cache keeps the runtime loading path (`loadAddon`) untouched:
 * install a fake at the start of a test run, pass `null` to restore the
 * real loader, and the shared cache stays consistent for everyone.
 */
export function setAddonForTesting(addon: TernAddon | null): void {
  cached = addon;
}

/**
 * The embedded platform addon for bundler-compiled executables (bun build
 * --compile). The literal dynamic imports below resolve at BUILD time: bun
 * embeds the matching `.node` into the executable, and the platform/arch
 * conditions fold per target so each binary carries exactly its own addon.
 * Under plain Node the import of a `.node`-mained package fails
 * (ERR_UNKNOWN_FILE_EXTENSION), under Deno it typically does not resolve —
 * both rejections are caught and the runtime `createRequire` loader below
 * serves those environments. The import runs at module load (top-level
 * await) so `loadAddon` stays synchronous: by the time any consumer calls
 * it, the embedded addon is resolved.
 */
async function loadEmbeddedAddon(): Promise<TernAddon | null> {
  try {
    if (process.platform === "darwin" && process.arch === "arm64") {
      // @ts-expect-error — the platform package is `.node`-mained (untyped).
      return (await import("@tern-tui/node-darwin-arm64")) as unknown as TernAddon;
    }
    if (process.platform === "darwin" && process.arch === "x64") {
      // @ts-expect-error — the platform package is `.node`-mained (untyped).
      return (await import("@tern-tui/node-darwin-x64")) as unknown as TernAddon;
    }
    if (process.platform === "linux" && process.arch === "x64") {
      // @ts-expect-error — the platform package is `.node`-mained (untyped).
      return (await import("@tern-tui/node-linux-x64-gnu")) as unknown as TernAddon;
    }
    if (process.platform === "linux" && process.arch === "arm64") {
      // @ts-expect-error — the platform package is `.node`-mained (untyped).
      return (await import("@tern-tui/node-linux-arm64-gnu")) as unknown as TernAddon;
    }
    if (process.platform === "win32" && process.arch === "x64") {
      // @ts-expect-error — the platform package is `.node`-mained (untyped).
      return (await import("@tern-tui/node-win32-x64-msvc")) as unknown as TernAddon;
    }
  } catch {
    // No embeddable candidate (or the import failed): fall through to the
    // runtime loader.
  }
  return null;
}

const embeddedAddon: TernAddon | null = await loadEmbeddedAddon();

/**
 * Load the tern-node addon (cached). A bundler-compiled executable uses the
 * statically embedded platform addon (see [`loadEmbeddedAddon`]); every
 * other runtime tries the npm package-name candidate first
 * (`@tern-tui/node`, how the binding is published for npm-installed
 * consumers), then the napi-generated loader (`index.js`), and finally
 * falls back to requiring the platform `.node` directly.
 *
 * Throws with the combined loader errors when no candidate resolves.
 */
export function loadAddon(): TernAddon {
  if (cached !== null) return cached;
  if (embeddedAddon !== null) {
    cached = embeddedAddon;
    return cached;
  }
  const require = createRequire(import.meta.url);
  const errors: string[] = [];
  const candidates = [
    // npm-installed consumers resolve the published binding package
    // `@tern-tui/node`. In the workspace this name does not resolve and
    // falls through to `tern-node` below.
    "@tern-tui/node",
    // Package-name resolution next: `packages/core` declares `tern-node` as
    // a dependency, so `createRequire` walks up to the workspace symlink at
    // the repo root (`node_modules/tern-node` -> `src/bindings/tern-node`).
    "tern-node",
    ADDON_PATH,
    `../../../src/bindings/tern-node/tern-node.${process.platform}-${process.arch}.node`,
  ];
  for (const candidate of candidates) {
    try {
      cached = require(candidate) as TernAddon;
      return cached;
    } catch (err) {
      errors.push(`${candidate}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  throw new Error("could not load the tern-node addon:\n" + errors.join("\n"));
}
