/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A handle to a scene node: either bound into the shared scene (`id` set) or
 * a detached template built by `create_node` that `add_child` materializes.
 *
 * `kind` / `style` / `props` are kept on the handle as the source of truth
 * for materialization and `set_props`.
 */
export declare class NodeHandle {
  /**
   * Materialize `child` (a detached `create_node` template) into the scene
   * under this node and return the bound child handle, so calls can chain
   * (`root.add_child(create_node(...))`). Errors when `self` is detached
   * or `child` already has a parent.
   */
  add_child(child: NodeHandle): NodeHandle
  /**
   * Materialize `child` (a detached `create_node` template) into the scene
   * under this node, positioned immediately before `anchor` in this node's
   * children, and return the bound child handle so calls can chain
   * (`parent.insert_before(create_node(...), existing_child)`).
   *
   * `anchor` must be an already-attached child of this node (in this node's
   * scene); `child` must still be detached. Errors when `self` is detached,
   * `child` already has a parent, or `anchor` is detached / not a child of
   * this node.
   */
  insert_before(child: NodeHandle, anchor: NodeHandle): NodeHandle
  /**
   * Detach this node (and its whole subtree) from the scene. Returns
   * `false` when the node was already detached (or is the scene root).
   */
  remove(): boolean
  /**
   * Replace this node's props (and style keys) in the scene.
   *
   * Recognized style keys are lifted out of the props object: `fg`, `bg`
   * (color strings), `border_style` (`none|plain|rounded|double|thick`),
   * and the boolean modifiers (`bold`, `dim`, `italic`, `underline`,
   * `blink`, `reversed`, `hidden`, `strikethrough`). Every other key lands
   * in the node's property map (`text`, layout keywords, ...).
   */
  set_props(props: Record<string, any>): void
  /**
   * Append a styled span of text to a `streaming_text` node's stream.
   *
   * `style` follows the same style-key convention as `set_props` (`fg`,
   * `bg`, `border_style`, and the boolean modifiers are lifted into the
   * span's style; every other key is ignored). The span is appended to the
   * node's accumulated stream in the shared scene, in call order. Errors
   * when the node is detached from the scene or is not a `streaming_text`
   * node.
   */
  append_span(text: string, style?: Record<string, any> | undefined | null): void
  /**
   * The laid-out content size of this node: `{ width, height }` in cells.
   *
   * For `text` / `streaming_text` nodes this is the wrapped content size
   * (the display width of the widest wrapped line and the wrapped line
   * count at the node's laid-out width); for containers it is the laid-out
   * rect size. The layout runs at the viewport of the most recent
   * [`TuiRenderer::render`], so the geometry matches what is on screen. A
   * node with no geometry (`display: none`) reports `(0, 0)`; a detached
   * handle errors.
   */
  content_size(): ContentSize
}

/**
 * The terminal-facing renderer: owns raw mode + alternate screen, polls
 * input, and paints the shared scene to the terminal.
 */
export declare class TuiRenderer {
  /**
   * Enter raw mode + the alternate screen, ready to render. Mouse and
   * focus-change event delivery is enabled so `poll_events` can surface
   * them.
   *
   * If any terminal transition fails the already-entered states are rolled
   * back before the error is returned, so a failed constructor never leaves
   * the terminal in raw mode.
   */
  constructor(options: TuiRendererOptions)
  /** A handle to the scene root, to attach content under. */
  root(): NodeHandle
  /**
   * Block up to `timeout_ms` for input, returning every event that arrived
   * in that window (a burst of events comes back as one batch).
   *
   * Key, resize, focus, and mouse events are all surfaced (mouse and focus
   * delivery is enabled in the constructor). With `exit_on_ctrl_c` enabled,
   * a Ctrl+C press tears the renderer down instead of being returned;
   * subsequent calls error until a new renderer is constructed.
   */
  poll_events(timeoutMs: number): Array<TernEventJs>
  /**
   * The scene node ids covering the cell at (`col`, `row`), innermost
   * (topmost) first, then each ancestor that also covers the cell. The
   * scene root is never reported; a cell no node covers yields `[]`.
   *
   * Z-order and clip/scroll regions match what [`render`](Self::render)
   * paints at the current terminal size, so a click at a mouse event's
   * `column`/`row` routes to the node that is visually on top.
   */
  hit_test(col: number, row: number): Array<bigint>
  /**
   * Paint the shared scene into a fresh buffer at the current terminal
   * size and flush the minimal diff (vs the previous frame) to the
   * terminal.
   */
  render(): void
  /**
   * Leave the alternate screen and raw mode and stop event listening,
   * restoring the terminal. Safe to call more than once; a destroyed
   * renderer cannot render or poll.
   */
  destroy(): void
  /**
   * Whether the renderer has been destroyed (explicitly or via Ctrl+C with
   * `exit_on_ctrl_c`).
   */
  get destroyed(): boolean
}

/** The laid-out content size of a scene node, in cells. */
export interface ContentSize {
  /** The content width in cells. */
  width: number
  /** The content height in cells. */
  height: number
}

/**
 * Create a detached node template of `type` (`"box"`, `"text"`, or
 * `"streaming_text"`) with `props`. The handle is materialized into the scene
 * when it is added to a bound parent via `NodeHandle.add_child`. See
 * `set_props` for the style-key convention.
 */
export declare function create_node(type: string, props?: Record<string, any> | undefined | null): NodeHandle

/**
 * A key event surfaced to JS as a plain object: `{ name, char, ctrl, alt,
 * shift }`. `char` is the printable character for `"char"`-named keys
 * (single-character string), `undefined` for named keys.
 */
export interface KeyEvent {
  /**
   * The key's name: `char`, `enter`, `escape`, `backspace`, `tab`,
   * `backtab`, `delete`, `insert`, `home`, `end`, `pageup`, `pagedown`,
   * `up`, `down`, `left`, `right`, `f<n>`, `null`, `unknown`.
   */
  name: string
  /** The printable character for `"char"` keys. */
  char?: string
  /** Whether Control was held. */
  ctrl: boolean
  /** Whether Alt (Option) was held. */
  alt: boolean
  /** Whether Shift was held. */
  shift: boolean
}

/**
 * A mouse event surfaced to JS as a plain object.
 *
 * `kind` encodes both the action and — where relevant — the button, so no
 * button information is lost: `"down_left"`, `"up_right"`,
 * `"drag_middle"`, `"moved"`, `"scroll_up"`, `"scroll_down"`,
 * `"scroll_left"`, `"scroll_right"`. `column` / `row` are the cell the
 * event occurred on (0-based); `ctrl` / `alt` / `shift` are the held
 * modifiers.
 */
export interface MouseEventJs {
  /**
   * The action + button, e.g. `"down_left"`, `"up_right"`,
   * `"drag_middle"`, `"moved"`, `"scroll_up"`.
   */
  kind: string
  /** The column the event occurred on (0-based). */
  column: number
  /** The row the event occurred on (0-based). */
  row: number
  /** Whether Control was held. */
  ctrl: boolean
  /** Whether Alt (Option) was held. */
  alt: boolean
  /** Whether Shift was held. */
  shift: boolean
}

/**
 * A terminal event surfaced to JS as a tagged-union plain object: `type`
 * discriminates (`"key"`, `"resize"`, `"focus"`, `"mouse"`) and exactly one
 * of `key` / `width`+`height` / `focus_gained` / `mouse` is set. For
 * `"focus"`, `focus_gained` is `true` on gained and `false` on lost.
 */
export interface TernEventJs {
  /** The event kind: `"key"`, `"resize"`, `"focus"`, or `"mouse"`. */
  type: string
  /** The key event, when `type` is `"key"`. */
  key?: KeyEvent
  /** The new width in columns, when `type` is `"resize"`. */
  width?: number
  /** The new height in rows, when `type` is `"resize"`. */
  height?: number
  /**
   * Whether focus was gained (`true`) or lost (`false`), when `type` is
   * `"focus"`.
   */
  focus_gained?: boolean
  /** The mouse event, when `type` is `"mouse"`. */
  mouse?: MouseEventJs
}

/** Constructor options for [`TuiRenderer`]. */
export interface TuiRendererOptions {
  /**
   * When `true`, a Ctrl+C key press tears the terminal down (raw mode +
   * alternate screen exited) and marks the renderer destroyed instead of
   * being surfaced as an event.
   */
  exit_on_ctrl_c?: boolean
}
