/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * An incremental token highlighter: buffers the accumulated source and
 * re-parses only the tail on each [`append`](Self::append), reusing the
 * previous tree so tree-sitter skips the untouched head. The one-shot
 * [`highlight`] re-parses the whole source per call; this class exists for
 * streaming consumers (a growing Markdown fence) where only the tail
 * changes between renders.
 *
 * Shared state lives behind `Arc<Mutex<_>>`, the binding's standard pattern
 * (see [`NodeHandle`](crate::NodeHandle)): the class instance stays
 * `Send + Sync` and every method is safe to call from the JS thread.
 */
export declare class IncrementalHighlighter {
  /**
   * Build a highlighter for `language` (a Markdown fence info string,
   * exactly like [`highlight`]). Errors on unknown languages or when the
   * grammar fails to load.
   */
  constructor(language: string)
  /**
   * Append `chunk` to the buffered source and return the complete span
   * stream over the accumulated text, plus the byte range the incremental
   * re-parse reworked (`None` before the first append). An empty chunk is
   * a no-op: no spans, no changed range.
   */
  append(chunk: string): HighlightAppendJs
  /**
   * Drop the buffered source and the parse tree; the next
   * [`append`](Self::append) is a full parse from scratch (and reports no
   * changed range, like any first append).
   */
  reset(): void
}

/**
 * A handle to a scene node: either bound into the shared scene (`id` set) or
 * a detached template built by `create_node` that `add_child` materializes.
 *
 * `kind` / `style` / `props` are kept on the handle as the source of truth
 * for materialization and `set_props`.
 */
export declare class NodeHandle {
  /**
   * Materialize `child` (a detached `create_node` template) into the scene
   * under this node and return the bound child handle, so calls can chain
   * (`root.add_child(create_node(...))`). Errors when `self` is detached
   * or `child` already has a parent.
   */
  add_child(child: NodeHandle): NodeHandle
  /**
   * Materialize `child` (a detached `create_node` template) into the scene
   * under this node, positioned immediately before `anchor` in this node's
   * children, and return the bound child handle so calls can chain
   * (`parent.insert_before(create_node(...), existing_child)`).
   *
   * `anchor` must be an already-attached child of this node (in this node's
   * scene); `child` must still be detached. Errors when `self` is detached,
   * `child` already has a parent, or `anchor` is detached / not a child of
   * this node.
   */
  insert_before(child: NodeHandle, anchor: NodeHandle): NodeHandle
  /**
   * Detach this node (and its whole subtree) from the scene. Returns
   * `false` when the node was already detached (or is the scene root).
   */
  remove(): boolean
  /**
   * Replace this node's props (and style keys) in the scene.
   *
   * Recognized style keys are lifted out of the props object: `fg`, `bg`,
   * `border_color` (color strings), `border_style`
   * (`none|plain|rounded|double|thick`), and the boolean modifiers
   * (`bold`, `dim`, `italic`, `underline`, `blink`, `reversed`, `hidden`,
   * `strikethrough`). Every other key lands in the node's property map
   * (`text`, layout keywords, ...).
   */
  set_props(props: Record<string, any>): void
  /**
   * Set a single property (or style key) on this node — the incremental
   * counterpart of [`set_props`](Self::set_props): one key instead of the
   * whole object.
   *
   * Recognized style keys (`fg`, `bg`, `border_color`, `border_style`, the
   * boolean modifiers) are merged into the node's existing style; every
   * other scalar key lands in the node's property map. Non-scalar values
   * (null, arrays, objects) are dropped, exactly like `set_props`.
   *
   * An equal-value write is a no-op: the scene is not mutated and its
   * epoch is not bumped, so a renderer's cached frame stays valid.
   */
  set_prop(key: string, value: any): void
  /**
   * Append a styled span of text to a `streaming_text` node's stream.
   *
   * `style` follows the same style-key convention as `set_props` (`fg`,
   * `bg`, `border_color`, `border_style`, and the boolean modifiers are
   * lifted into the span's style; every other key is ignored). The span is
   * appended to the node's accumulated stream in the shared scene, in call
   * order. Errors when the node is detached from the scene or is not a
   * `streaming_text` node.
   */
  append_span(text: string, style?: Record<string, any> | undefined | null): void
  /**
   * The laid-out content size of this node: `{ width, height }` in cells.
   *
   * For `text` / `streaming_text` nodes this is the wrapped content size
   * (the display width of the widest wrapped line and the wrapped line
   * count at the node's laid-out width); for containers it is the laid-out
   * rect size. The layout runs at the viewport of the most recent
   * [`TuiRenderer::render`], so the geometry matches what is on screen. A
   * node with no geometry (`display: none`) reports `(0, 0)`; a detached
   * handle errors.
   */
  content_size(): ContentSize
}

/**
 * The terminal-facing renderer: owns raw mode + alternate screen, pushes
 * input to the JS thread via a threadsafe event stream (or polls it with the
 * `poll-fallback` feature), and paints the shared scene to the terminal.
 */
export declare class TuiRenderer {
  /**
   * Enter raw mode + the alternate screen (unless `use_alt_screen` is
   * `false`), apply the window title, and enable mouse / focus-change /
   * bracketed-paste event delivery, ready to render. The kitty keyboard
   * protocol enhancement is pushed only when opted in (default) and the
   * interactive probe reports the terminal supports it.
   *
   * If any terminal transition fails the already-entered states are rolled
   * back before the error is returned, so a failed constructor never leaves
   * the terminal in raw mode.
   */
  constructor(options: TuiRendererOptions)
  /** A handle to the scene root, to attach content under. */
  root(): NodeHandle
  /**
   * The scene node ids covering the cell at (`col`, `row`), innermost
   * (topmost) first, then each ancestor that also covers the cell. The
   * scene root is never reported; a cell no node covers yields `[]`.
   *
   * Z-order and clip/scroll regions match what [`render`](Self::render)
   * paints at the current terminal size, so a click at a mouse event's
   * `column`/`row` routes to the node that is visually on top.
   */
  hit_test(col: number, row: number): Array<bigint>
  /**
   * Paint the shared scene into a fresh buffer at the current terminal
   * size and flush the minimal diff (vs the previous frame) to the
   * terminal — a single DECSTBM + SU/SD scroll command plus the newly
   * exposed rows when the diff is exactly a vertical scroll of a
   * full-width row band and the terminal supports scroll-region painting
   * (the M2.1 fast path, opt-in via `scroll_optimization`).
   *
   * No-op fast path: when the scene has not mutated since the last paint
   * and the viewport is unchanged, the previous frame is still on screen,
   * so the render returns `Ok(())` without the size probe, paint, diff,
   * flush, or buffer storage — zero terminal writes for an unchanged
   * frame (the high-frame-rate path: JS re-renders every animation tick,
   * but only real changes pay for I/O).
   */
  render(): void
  /**
   * Paint the shared scene into a fresh buffer at the given viewport —
   * `width`/`height` in cells, each defaulting to the most recent
   * [`render`](Self::render) terminal size — and return the frame as one
   * string per row. Masked/continuation cells (the zero-width right
   * halves of wide glyphs) are spaces, so every row has exactly `width`
   * display columns (multi-width aware). Performs no terminal I/O; the
   * result is a pure snapshot for JS-side testing and golden
   * comparisons.
   */
  render_to_buffer(width?: number | undefined | null, height?: number | undefined | null): Array<string>
  /**
   * Paint the shared scene into a fresh buffer at the given viewport —
   * `width`/`height` in cells, each defaulting to the most recent
   * [`render`](Self::render) terminal size — and return the frame as one
   * vector of styled runs per row. Each run is `{ text, fg?, bg?, bold?,
   * dim?, italic?, underline?, reversed?, strikethrough? }`; adjacent cells
   * with identical style merge into one run, and concatenating a row's run
   * texts reconstructs the [`render_to_buffer`](Self::render_to_buffer)
   * row string exactly (masked/continuation cells are spaces, multi-width
   * aware). Colors surface as `"#rrggbb"` (truecolor) or `"indexed:<n>"`
   * (palette) strings; modifier keys are present only when set. Shares
   * [`render_to_buffer`](Self::render_to_buffer)'s paint path and viewport
   * recording semantics (and its destroyed-renderer error); performs no
   * terminal I/O, so the result is a pure styled snapshot for JS-side
   * testing and golden comparisons.
   */
  render_to_buffer_styled(width?: number | undefined | null, height?: number | undefined | null): Array<Array<StyleRunJs>>
  /**
   * Leave the alternate screen and raw mode and stop event listening,
   * restoring the terminal. Any-event mouse tracking is turned off
   * (`?1003l`) before the general event-listening disable, so the
   * terminal closes its capture modes in enable order. Also stops the
   * push event loop (with the default `push-events` feature) so the
   * loop thread exits, and stops the signal thread so the process's
   * signal dispositions are restored. Safe to call more than once; a
   * destroyed renderer cannot render or poll.
   */
  destroy(): void
  /**
   * Whether the renderer has been destroyed (explicitly or via Ctrl+C with
   * `exit_on_ctrl_c`).
   */
  get destroyed(): boolean
  /**
   * The terminal's capabilities: the color report detected once by the
   * backend (`{ truecolor, colors }` — see `tern-terminal`'s
   * `Backend::capabilities`) merged with the interactive probe report
   * (`terminalIdentity`, `kittyKeyboard`, `kittyUnderline`, `osc52`,
   * `bracketedPaste`, `focusEvents`, `scrollRegion`, `probed` — see
   * `tern-terminal`'s `probe::TerminalCapabilities`). The probe result is
   * cached per process; a probe skipped for a non-TTY or `TERM=dumb`
   * reports conservative defaults with `probed: false`.
   */
  get capabilities(): RendererCapabilities
  /**
   * The number of bytes the most recent `render()` flush queued to the
   * terminal: the ANSI escape-sequence stream for that frame's diff (0 for
   * a fully suppressed empty-diff frame). Fed by the backend queue via the
   * flush return value; a no-op fast-path render (scene unchanged) never
   * flushes, so the counter keeps the previous flush's value until the next
   * real flush. The byte-cost measure behind the bench's
   * flushed-bytes-per-frame numbers.
   */
  get last_flush_bytes(): bigint
  /**
   * Set the terminal window title (OSC 0). Errors on a destroyed
   * renderer.
   */
  set_title(title: string): void
  /**
   * The terminal size as `{ width, height }` in cells: the viewport the
   * most recent [`render`](Self::render) or
   * [`render_to_buffer`](Self::render_to_buffer) painted at (80x24 before
   * any paint).
   *
   * Before the first paint no real viewport exists yet, so the first
   * access seeds the default from the terminal through the cached-size
   * machinery — the cache when it is still valid, otherwise a
   * [`RenderBackend::size`] probe (refreshing the cache) — and records the
   * probed size as the shared scene viewport: a fresh renderer reports the
   * current terminal size instead of the synthetic 80x24 fallback, and its
   * snapshot/content-size defaults match. After any paint the last painted
   * viewport is authoritative and no probe happens. Errors on a destroyed
   * renderer.
   */
  get size(): RendererSize
  /**
   * Copy `text` to the system clipboard (OSC 52: `ESC ] 52 ; c ; <base64>
   * BEL`, the payload being the text's UTF-8 bytes base64-encoded). Errors
   * on a destroyed renderer.
   */
  set_clipboard(text: string): void
  /**
   * Enable or disable any-event mouse tracking (`?1003h` / `?1003l`):
   * the terminal reports every mouse motion while enabled, not just
   * presses and drags. Off by default — the constructor enables
   * press/release, drag, and scroll tracking only — so motion events
   * flow only while a motion/drag listener is registered. Records the
   * state so [`destroy`](Self::destroy) turns the mode off (`?1003l`)
   * before the general event-listening disable. Errors on a destroyed
   * renderer.
   */
  set_any_event_mouse(enabled: boolean): void
  /**
   * Set the selection overlay to the inclusive rectangle spanned by
   * (`col1`, `row1`) and (`col2`, `row2`) in viewport cells. The endpoints
   * are normalized by the compositor, so either may be the top-left. The
   * overlay is applied at the next [`render`](Self::render) (which the
   * selection edit forces) and to the next
   * [`render_to_buffer`](Self::render_to_buffer) snapshot. Per-renderer
   * state — the shared scene never carries the selection. Errors on a
   * destroyed renderer.
   */
  set_selection(col1: number, row1: number, col2: number, row2: number): void
  /**
   * Clear the selection overlay: the next render paints without any
   * reversed selection cells (and the next snapshot omits the overlay).
   * Errors on a destroyed renderer.
   */
  clear_selection(): void
  /**
   * Set the renderer's caret override: position (`x`, `y`), shape
   * (`"block"` / `"bar"` / `"underline"`), visibility, and blinking, all
   * in viewport cells / DECSCUSR terms. The next [`render`](Self::render)
   * (which the cursor edit forces) flushes through the cursor-aware path:
   * the frame diff, then `MoveTo` + `SetCursorStyle` (nothing for the
   * default steady block) + `Show`/`Hide` for the caret, so the hardware
   * caret tracks the model. Errors on a destroyed renderer or an
   * unrecognized shape string.
   */
  set_cursor(x: number, y: number, shape: string, visible: boolean, blink: boolean): void
  /**
   * Clear the renderer's caret override: the next [`render`](Self::render)
   * (which the cursor edit forces) falls back to the legacy position-only
   * flush — the frame diff with the caret parked at the top-left, no
   * shape, blinking, or visibility control — byte-identical to a renderer
   * that never called [`set_cursor`](Self::set_cursor). Errors on a
   * destroyed renderer.
   */
  clear_cursor(): void
  /**
   * The text of the renderer's current selection, extracted from the last
   * painted frame (the frame the most recent [`render`](Self::render)
   * produced): row-major and cluster/mask-aware — a multi-char cluster
   * (ZWJ emoji, combining sequence, flag) contributes its whole symbol, a
   * masked continuation cell contributes nothing, and rows are joined
   * with `'
  '`. An empty string when no selection is set or nothing has
   * been rendered yet. Errors on a destroyed renderer.
   */
  selection_text(): string
  /**
   * The inclusive cell range of the contiguous non-whitespace run (word)
   * containing (`col`, `row`) in the last painted frame, or `null` when
   * the cell is blank/whitespace (or out of bounds, or nothing has been
   * rendered yet).
   *
   * Cluster-aware: a masked continuation cell (the right half of a wide
   * glyph) is treated as part of its glyph's run — never as whitespace —
   * so a click on a wide character's second column still returns the word
   * that contains the glyph. Errors on a destroyed renderer.
   */
  selection_word_range(col: number, row: number): SelectionRange | null
  /**
   * Start push-based event delivery: spawn tern-terminal's background
   * event loop and deliver every normalized terminal event to `callback`
   * on the JS thread through a threadsafe function.
   *
   * Events arrive in arrival order and none are dropped (the threadsafe
   * queue is unbounded), so the JS renderer subscribes instead of polling.
   * Key, resize, focus, mouse, and paste events are all delivered (mouse,
   * focus, and bracketed-paste delivery is enabled in the constructor).
   * With `exit_on_ctrl_c` enabled, a Ctrl+C press is delivered and then
   * tears the renderer down (marked destroyed; the loop stops). Destroying
   * the renderer also stops the loop. Errors if the renderer is already
   * destroyed or a stream was already started.
   */
  start_event_stream(callback: ((err: Error | null, arg: TernEventJs) => any)): void
}

/** The laid-out content size of a scene node, in cells. */
export interface ContentSize {
  /** The content width in cells. */
  width: number
  /** The content height in cells. */
  height: number
}

/**
 * Create a detached node template of `type` (`"box"`, `"text"`, or
 * `"streaming_text"`) with `props`. The handle is materialized into the scene
 * when it is added to a bound parent via `NodeHandle.add_child`. See
 * `set_props` for the style-key convention.
 */
export declare function create_node(node_type: string, props?: Record<string, any> | undefined | null): NodeHandle

/**
 * Token-highlight `source` in `language` (a Markdown fence info string:
 * `"rust"` / `"typescript"` / `"ts"` / `"tsx"` / `"javascript"` / `"js"` /
 * `"json"` / `"bash"` / `"shell"` / `"sh"` / `"zsh"`) into a complete span
 * stream for a code fence or a `streaming_text` node.
 *
 * The returned spans cover every byte of `source` (gaps carry no style) and
 * merge adjacent same-style runs, so concatenating their `text` reconstructs
 * the source exactly — the compositor paints them in order. Unknown
 * languages error; tree-sitter is error-tolerant, so half-open streaming
 * input still highlights.
 */
export declare function highlight(language: string, source: string): Array<HighlightSpanJs>

/**
 * The result of one [`IncrementalHighlighter::append`]: the *complete* span
 * stream over the accumulated source (every byte covered, gaps unstyled,
 * equal-style neighbors merged — concatenating the span texts reconstructs
 * the source exactly) plus the byte range the incremental re-parse actually
 * reworked.
 *
 * `changed` is the `[start, end)` byte span the engine's
 * `last_changed_span` reported for the append — the union of tree-sitter's
 * changed ranges between the pre- and post-append trees, so a pure tail
 * append reports a range within the appended chunk. It is `None` before the
 * first append (or after a `reset`), when there was no previous parse to
 * change. This DTO is output-only (`object_from_js = false`): it is
 * returned to JS, never accepted as an argument — which also lets the
 * `changed` range be a fixed `[u32; 2]` pair rather than a `Vec`.
 */
export interface HighlightAppendJs {
  /** The complete span stream over the accumulated source. */
  spans: Array<HighlightSpanJs>
  /**
   * The `[start, end)` byte range the incremental parse reworked, `None`
   * before the first append (no previous state to change).
   */
  changed?: number[]
}

/**
 * One token-highlighted span: the chunk's text plus the style keys lifted
 * from the highlight style (`fg` as a `"#rrggbb"` hex string, and the boolean
 * modifiers). The shape mirrors `Span` (the `append_span` style-key
 * convention), so a JS consumer can feed a highlighted span straight into a
 * `streaming_text` node.
 */
export interface HighlightSpanJs {
  /** The span's text content. */
  text: string
  /** The foreground color as `"#rrggbb"`, when the token carries one. */
  fg?: string
  /** Whether the token is bold. */
  bold: boolean
  /** Whether the token is italic. */
  italic: boolean
  /** Whether the token is dim. */
  dim: boolean
  /** Whether the token is underlined. */
  underline: boolean
}

/**
 * A key event surfaced to JS as a plain object: `{ name, char, ctrl, alt,
 * shift, kind, super, meta, hyper }`. `char` is the printable character for
 * `"char"`-named keys (single-character string), `undefined` for named
 * keys. `kind` is `"press"` (the default — the only kind a terminal without
 * the kitty keyboard protocol reports), `"repeat"`, or `"release"`; the
 * precise modifier keys (`super`, `meta`, `hyper`) are present only when
 * held. `name`/`char`/`ctrl`/`alt`/`shift` are unchanged for back-compat.
 */
export interface KeyEvent {
  /**
   * The key's name: `char`, `enter`, `escape`, `backspace`, `tab`,
   * `backtab`, `delete`, `insert`, `home`, `end`, `pageup`, `pagedown`,
   * `up`, `down`, `left`, `right`, `f<n>`, `null`, `unknown`.
   */
  name: string
  /** The printable character for `"char"` keys. */
  char?: string
  /** Whether Control was held. */
  ctrl: boolean
  /** Whether Alt (Option) was held. */
  alt: boolean
  /** Whether Shift was held. */
  shift: boolean
  /**
   * The key event kind: `"press"` (default), `"repeat"`, or `"release"`.
   * Filled by [`KeyEvent::from_tern`] from the tern [`KeyKind`].
   */
  kind?: string
  /** Whether Super (the Windows / Command key) was held. */
  super?: boolean
  /** Whether Meta was held. */
  meta?: boolean
  /** Whether Hyper was held. */
  hyper?: boolean
}

/**
 * A lifecycle event surfaced to JS when the renderer's owning process is
 * suspended or resumed by a job-control signal (SIGTSTP / SIGCONT): `type`
 * is `"lifecycle"` and `lifecycle.phase` is `"suspend"` or `"resume"`.
 *
 * `"suspend"` is pushed right before the process re-raises SIGTSTP to stop
 * (the terminal has been restored to its pre-renderer state — the JS side
 * can flush anything it must persist before the stop). `"resume"` is pushed
 * after the process re-entered raw mode + the alternate screen and forced a
 * full repaint (the size cache and retained frame were invalidated), so the
 * app knows the screen is live again and must re-render.
 */
export interface LifecycleEvent {
  /**
   * `"suspend"` (terminal restored, process about to stop) or `"resume"`
   * (terminal re-entered, full repaint pending).
   */
  phase: string
}

/**
 * A mouse event surfaced to JS as a plain object.
 *
 * `kind` encodes both the action and — where relevant — the button, so no
 * button information is lost: `"down_left"`, `"up_right"`,
 * `"drag_middle"`, `"moved"`, `"scroll_up"`, `"scroll_down"`,
 * `"scroll_left"`, `"scroll_right"`. `column` / `row` are the cell the
 * event occurred on (0-based); `ctrl` / `alt` / `shift` are the held
 * modifiers.
 */
export interface MouseEventJs {
  /**
   * The action + button, e.g. `"down_left"`, `"up_right"`,
   * `"drag_middle"`, `"moved"`, `"scroll_up"`.
   */
  kind: string
  /** The column the event occurred on (0-based). */
  column: number
  /** The row the event occurred on (0-based). */
  row: number
  /** Whether Control was held. */
  ctrl: boolean
  /** Whether Alt (Option) was held. */
  alt: boolean
  /** Whether Shift was held. */
  shift: boolean
}

/**
 * The terminal's capabilities, surfaced by the `capabilities` getter: the
 * color report detected once by the backend (see
 * [`backend::capabilities`](crate::backend::capabilities)) merged with the
 * interactive probe report (see
 * [`tern_terminal::probe::TerminalCapabilities`]): terminal identity plus
 * the kitty keyboard / underline, OSC 52, bracketed-paste, and focus-event
 * protocol supports the terminal itself reported during the probe.
 */
export interface RendererCapabilities {
  /** Whether 24-bit (16M) RGB truecolor is supported. */
  truecolor: boolean
  /**
   * The terminal's color palette size: 16_777_216 for truecolor, 256 for
   * a 256-color palette, 16 for basic ANSI, 0 when none.
   */
  colors: number
  /**
   * The terminal's self-reported identity from the interactive probe: the
   * XTVERSION text when the terminal answers it (e.g. `kitty(0.36.0)`),
   * else the XTGETTCAP `TN` capability value, else the raw DA2
   * `Pp;Pv;Pc` identification code. `null` when no reply named the
   * terminal (or the probe was skipped for a non-TTY / `TERM=dumb`).
   */
  terminalIdentity?: string
  /**
   * Whether the kitty keyboard protocol is supported, as reported by the
   * interactive probe (`fullkbd`/`XK` XTGETTCAP). `false` for a terminal
   * that did not answer the probe, so the backend keeps the legacy key
   * reporting fallback.
   */
  kittyKeyboard: boolean
  /**
   * Whether kitty extended underline styles are supported
   * (`Su`/`Setulc` XTGETTCAP: `CSI 4:N m` variants and colored
   * underlines), as reported by the interactive probe. `false` for an
   * unknown terminal, which takes the plain `CSI 4 m` fallback.
   */
  kittyUnderline: boolean
  /**
   * Whether OSC 52 clipboard writes are supported: the DA1 parameter `52`
   * (the contour clipboard-extension marker), or an XTGETTCAP `Ms`
   * reply, as reported by the interactive probe.
   */
  osc52: boolean
  /**
   * Whether bracketed paste mode is supported (XTGETTCAP `PS`/`BE`), as
   * reported by the interactive probe. `false` filters paste events at
   * the event layer.
   */
  bracketedPaste: boolean
  /**
   * Whether focus in/out events are supported (XTGETTCAP `XF`), as
   * reported by the interactive probe. `false` keeps focus-event
   * reporting disabled.
   */
  focusEvents: boolean
  /**
   * Whether the terminal supports scroll-region (DECSTBM) painting, as
   * derived from the interactive probe: a self-identified terminal that
   * is not tmux or screen (whose DECSTBM quirks make scroll-region
   * painting unsafe) gets the scroll optimization. `false` for an
   * unknown or silent terminal, which keeps the full-screen redraw
   * fallback.
   */
  scrollRegion: boolean
  /**
   * Whether the interactive probe parsed any query reply. `false` when
   * the probe was skipped (non-TTY or `TERM=dumb`) or every query went
   * unanswered (timeout / empty reply); every probe field is then a
   * conservative default.
   */
  probed: boolean
}

/**
 * The terminal size reported by a [`TuiRenderer`]: `{ width, height }` in
 * cells.
 */
export interface RendererSize {
  /** The width in columns. */
  width: number
  /** The height in rows. */
  height: number
}

/**
 * An inclusive cell range, in viewport coordinates: the rectangle spanned
 * by (`col1`, `row1`) and (`col2`, `row2`). Either endpoint may be the
 * top-left; consumers normalize with `min`/`max`.
 */
export interface SelectionRange {
  /** The column of one endpoint (inclusive). */
  col1: number
  /** The row of one endpoint (inclusive). */
  row1: number
  /** The column of the other endpoint (inclusive). */
  col2: number
  /** The row of the other endpoint (inclusive). */
  row2: number
}

/**
 * One styled run in a [`TuiRenderer::render_to_buffer_styled`] snapshot row:
 * the run's text plus the style keys its cells share. Adjacent cells with
 * identical style merge into one run, so concatenating a row's run texts
 * reconstructs the whole row (masked continuation cells as spaces, exactly
 * like the plain [`TuiRenderer::render_to_buffer`]).
 *
 * Colors surface as `"#rrggbb"` (truecolor) or `"indexed:<n>"` (ANSI
 * palette) strings; every modifier key is present only when set, so an
 * unstyled run carries just `text`. A run whose cells carry a hyperlink
 * reports the link target as `hyperlink` — the value the engine threads
 * from the `href` style key into `Style::hyperlink` (see
 * [`apply_style_key`](crate::convert::apply_style_key)). A run whose cells
 * carry an extended underline reports `underline_style` (the kitty
 * `\x1b[4:Nm` variant keyword) and `underline_color` — the values the
 * engine threads from the `underline_style` / `underline_color` style
 * keys into `Style::underline_style` / `Style::underline_color`; both are
 * present only when set.
 */
export interface StyleRunJs {
  /** The run's text content. */
  text: string
  /** The foreground color, when the cells carry one. */
  fg?: string
  /** The background color, when the cells carry one. */
  bg?: string
  /**
   * The hyperlink target (a URL) the run's cells paint as an OSC 8
   * hyperlink, present only when the cells carry one.
   */
  hyperlink?: string
  /**
   * The underline style variant the run's cells paint (`"single"`,
   * `"double"`, `"curly"`, `"dotted"`, or `"dashed"`), present only when
   * the cells carry one.
   */
  underlineStyle?: string
  /**
   * The color the run's underline is painted with, present only when the
   * cells carry one.
   */
  underlineColor?: string
  /** Whether the run is bold. */
  bold?: boolean
  /** Whether the run is dim. */
  dim?: boolean
  /** Whether the run is italic. */
  italic?: boolean
  /** Whether the run is underlined. */
  underline?: boolean
  /** Whether the run is reversed (fg/bg swapped). */
  reversed?: boolean
  /** Whether the run is struck through. */
  strikethrough?: boolean
}

/**
 * A terminal event surfaced to JS as a tagged-union plain object: `type`
 * discriminates (`"key"`, `"resize"`, `"focus"`, `"mouse"`, `"paste"`,
 * `"lifecycle"`) and exactly one of `key` / `width`+`height` /
 * `focus_gained` / `mouse` / `paste` / `lifecycle` is set. For `"focus"`,
 * `focus_gained` is `true` on gained and `false` on lost. `"lifecycle"`
 * events are pushed by the native signal thread (see
 * [`LifecycleEvent`]) and carry no terminal event.
 */
export interface TernEventJs {
  /**
   * The event kind: `"key"`, `"resize"`, `"focus"`, `"mouse"`, `"paste"`,
   * or `"lifecycle"`.
   */
  type: string
  /** The key event, when `type` is `"key"`. */
  key?: KeyEvent
  /** The new width in columns, when `type` is `"resize"`. */
  width?: number
  /** The new height in rows, when `type` is `"resize"`. */
  height?: number
  /**
   * Whether focus was gained (`true`) or lost (`false`), when `type` is
   * `"focus"`.
   */
  focus_gained?: boolean
  /** The mouse event, when `type` is `"mouse"`. */
  mouse?: MouseEventJs
  /** The pasted text, when `type` is `"paste"`. */
  paste?: string
  /**
   * The lifecycle phase (`"suspend"` / `"resume"`), when `type` is
   * `"lifecycle"` — pushed by the native signal thread, not the terminal.
   */
  lifecycle?: LifecycleEvent
}

/** Constructor options for [`TuiRenderer`]. */
export interface TuiRendererOptions {
  /**
   * When `true`, a Ctrl+C key press tears the terminal down (raw mode +
   * alternate screen exited) and marks the renderer destroyed instead of
   * being surfaced as an event.
   */
  exit_on_ctrl_c?: boolean
  /**
   * When `false`, the renderer skips the alternate screen: it renders
   * inline in the terminal's main screen (and never emits the alternate-
   * screen enter/leave escapes). Default `true`.
   */
  use_alt_screen?: boolean
  /**
   * The terminal window title, applied on construction (OSC 0). `None`
   * leaves the title untouched.
   */
  title?: string
  /**
   * When `true`, the renderer never touches a terminal: no raw mode, no
   * alternate screen, no event listening, no title. Rendering and
   * snapshots run against an in-memory buffer of the configured `width` x
   * `height` (default 80x24), so construction and rendering succeed
   * without a TTY (plain `cargo test`, CI, snapshot tooling). Default
   * `false`.
   */
  headless?: boolean
  /**
   * Enable the kitty keyboard protocol (progressive enhancement) so
   * modifier combinations like Shift-Enter arrive as distinct key events
   * instead of collapsing into the unmodified key. Terminals that do not
   * support the protocol ignore the sequences; the enhancement is popped
   * on destroy. Default `true`.
   */
  keyboard_enhancement?: boolean
  /**
   * When `false`, the renderer skips the scroll-region (DECSTBM) fast
   * path: a frame whose diff is exactly a vertical scroll of a full-width
   * region flushes as one terminal scroll command plus the newly exposed
   * rows instead of a cell-by-cell repaint. Only active on terminals the
   * interactive probe reports as scroll-region safe (never tmux/screen).
   * Default `true`.
   */
  scroll_optimization?: boolean
  /**
   * The virtual width in cells for `headless` mode (default 80). Ignored
   * when `headless` is `false`.
   */
  width?: number
  /**
   * The virtual height in cells for `headless` mode (default 24). Ignored
   * when `headless` is `false`.
   */
  height?: number
}
